# Generated by Django 5.2 on 2025-04-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('current_stock', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
